export enum ErrorCodes {
  INVALID_TIME_UNIT = 'INVALID_TIME_UNIT',
  INVALID_FORMAT_DATA = 'INVALID_FORMAT_DATA',
  INVALID_MS_VALUE = 'INVALID_MS_VALUE',
  INVALID_DB_SELECTION = 'INVALID_DB_SELECTION',
  INVALID_REPEAT_VALUE = 'INVALID_REPEAT_VALUE',
  INVALID_TYPE_VALUE = 'INVALID_TYPE_VALUE',
  REPEAT_NOT_ALLOWED = 'REPEAT_NOT_ALLOWED'
}