export enum ErrorCodes {
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  INVALID_TIME_UNIT = 'INVALID_TIME_UNIT',
  INVALID_FORMAT_DATA = 'INVALID_FORMAT_DATA',
  INVALID_MS_VALUE = 'INVALID_MS_VALUE',
  INVALID_DB_SELECTION = 'INVALID_DB_SELECTION'
}